### ISSUE TITLE
double submission

### ISSUE THREAD

**Issue by jenbrannstrom** [TapTapMobile/narconon#1]
each submission is sent twice: one correct, one incorrect.
Please see screenshot: http://prntscr.com/55wjjg
spreadsheet is here: https://docs.google.com/spreadsheets/d/1xh8ulQ99o4lYKDMl2eXq9fmvHrXXmHq_6r6cebqBx58/edit#gid=2091666274

**Comment by shailesh91** [comment]
I will have a look at this.

On Thursday, November 13, 2014, Jen Brannstrom notifications@github.com
wrote:

> Assigned #1 https://github.com/TapTapMobile/narconon/issues/1 to
> @shailesh91 https://github.com/shailesh91.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TapTapMobile/narconon/issues/1#event-192609342.

## 

## 

Regards
Shailesh Goel

Email   : shailesh912@gmail.com
Skype  : shailesh916
Phone  : +91-9780493275

**Comment by jenbrannstrom** [comment]
will not fix - have other solution
