### ISSUE TITLE
clone needs separate webform

### ISSUE THREAD

**Issue by jenbrannstrom** [TapTapMobile/narconon#11]
This page: http://lp.drug-education.co.uk/
has a webform powered by zappier, which feeds into a Google doc

to login to zapier:
user: jen.brannstrom@morequalifiedleads.co.uk
pass: zapier99
The page, along with thewebform has been cloned into http://lp.drug-education.co.uk/rehab.html
but the websubmissions should go to a separate sheet:

https://docs.google.com/spreadsheets/d/1BVUp1DiHvmRBRQ_FmxiJlQC6v3qxNfzlN9HGaqyl-3c/edit?usp=sharing

Sheet title: "rehab enquiries"
You will need to configure the field names on both the sheet and the form

Zap:
https://zapier.com/app/editor/5207078

**Comment by c3j333** [comment]
It is now functioning.
