### ISSUE TITLE
move to PHP email 

### ISSUE THREAD

**Issue by jenbrannstrom** [TapTapMobile/narconon#4]
There seems to be a conflict with the AdWords conversion tracking script and the Google sheets js. Rather than spend unknown hours on researching why this bug, I would prefer to just move the page to a known-to-be-working setup.
Please can you change the page to use PHP email submit.
This will mean we need a PHP server. We can use OpenShift, I will set up an account for this.

**Comment by shailesh91** [comment]
Jen, do you want to save the data in a mysql db for this?

**Comment by shailesh91** [comment]
Checked integration with zapier and google sheets. Works great!
