### ISSUE TITLE
Sharing and Countdown Javascript

### ISSUE THREAD

**Issue by shailesh91** [TapTapMobile/narconon#7]
Is the Code Sharing and Countdown timer required in this page?

**Comment by shailesh91** [comment]
The one already present are causing JS errors. So will need to replace them with a better solution. Which sharing button are needed and where should they exactly be placed?

**Comment by jenbrannstrom** [comment]
Just Fb share would be great.
Twitter share buttons are a pain, so leave that for now.

**Comment by shailesh91** [comment]
Where should the button be placed?

**Comment by shailesh91** [comment]
Plus you will have to create an app for this, because a native facebook share button requires an appid.

**Comment by jenbrannstrom** [comment]
floating right hand side, like this:
http://rawgit.com/dwhewitson/minishare/master/demo.html#
