### ISSUE TITLE
extra text space

### ISSUE THREAD

**Issue by jenbrannstrom** [TapTapMobile/narconon#8]
Please can you add three more sections, similar to this screenshot: http://prntscr.com/6b3nvs
this is taken from http://demos.bornthemes.com/landingpages/conversion/templates/home-01.html

Sections go at the bottom, under the "testimonial boxes"

**Comment by shailesh91** [comment]
3 sections have been added!

**Comment by jenbrannstrom** [comment]
I'm confused: where is the commit? I don't see it on any of the branches here in GitHub.
Did you commit it on OpenShift?

**Comment by shailesh91** [comment]
It is on OpenShift.

**Comment by jenbrannstrom** [comment]
WOOOW, such a nice job Shailesh :+1:

**Comment by shailesh91** [comment]
thanks!
