### ISSUE TITLE
required fields

### ISSUE THREAD

**Issue by jenbrannstrom** [TapTapMobile/narconon#9]
the submit form has no required fields, so a person can just click "send" and they will arrive on the thank you page.

Can we make the fields required: 
- Name 
- phone number

**Comment by shailesh91** [comment]
I will make them required.

**Comment by shailesh91** [comment]
Jen,
The page on this domain is not same as that on the openshift page. 
http://lp.drug-education.co.uk/
Although I have updated the openshit server.
Please check that.
